name: newpapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider:
  fl_chart: ^0.69.2
  flutter_lints: ^5.0.0
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  uuid: ^4.5.1
  flutter_slidable: ^3.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/kirby.jpg"


flutter:
  uses-material-design: true
